POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer 
{
  "title": "Hatsune Miku shares a crow fact!",
  "author": "Hatsune Miku",
  "content": "Hey guys its me Hatsune Miku! Did you know that crows can recognize human faces and remember them for years? They are also known to use tools and even hold grudges against specific individuals. Crows are incredibly intelligent birds with complex social structures. Fascinating, right?",
  "likes": 0  
}

