PUT http://localhost:3001/api/blogs/68751bb40aef74a66a6d776f
Content-Type: application/json

{
    "title": "Bobedy badebady",
    "author": "Jobeby badoby",
    "url": "joejoejoejoe.com",
    "likes": 12360
}